version: '3.8'

services:
  backend:
    build: ./app
    ports:
      - "8001:8001"
    environment:
      - DB_NAME=postgres
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db       # db service hostname instead of localhost
      - DB_PORT=5432
    depends_on:
      - db
    restart: always
      # Mount your code as a volume (optional, for development)

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"   # Exposing postgres on port 5433 on the host
    # volumes:
    #   - db_data:/var/lib/postgresql/data   # Persist database data
    restart: always

# volumes:
#   db_data:
